Add script mode
This is very rudimentary for now.

Signed-off-by: Andy Lutomirski <luto@amacapital.net>

diff --git a/virtme-init b/virtme-init
--- a/virtme-init
+++ b/virtme-init
@@ -95,6 +95,26 @@ if cat /proc/cmdline |grep -q -E '(^| )virtme.dhcp($| )'; then
     busybox udhcpc -i eth0 -t 1 -n -q -f -s "$(dirname $0)/virtme-udhcpc-script"
 fi
 
+# Implement script mode.  This could be improved considerably.
+if cat /proc/cmdline |grep -q -E '(^| )virtme.script='; then
+    script="`sed -nr -e 's/.*(^| )virtme\.script=([^ ]+)($| ).*/\2/p' /proc/cmdline`"
+
+    if [[ ! -e "/dev/virtio-ports/virtme.scriptio" ]]; then
+	echo "virtme-init: cannot find script I/O port; make sure virtio-serial is available"
+	poweroff -f
+	exit 1
+    fi
+
+    log 'starting script'
+    setsid "$script" <>"/dev/virtio-ports/virtme.scriptio" 2>&1
+    log "script returned $?"
+
+    # Hmm.  We should expose the return value somehow.
+    sync
+    poweroff -f
+    exit 1
+fi
+
 # Create some VTs
 deallocvt
 openvt -c 2 -- /bin/bash
