virtme-ng: channel the return code of a command to the host
Send the return code of the command executed inside the guest to the
host.

This allows to run commands inside a guest and give users the impression
that they are running on the host.

Examples:

  $ vng -r -- true && echo OK || echo ERROR: $?
  OK
  $ vng -r -- false && echo OK || echo ERROR: $?
  ERROR: 1
  $ vng -r -- exit 22 && echo OK || echo ERROR: $?
  ERROR: 22

This feature is particularly useful for automation/CI, since it easily
allows to check the return code of a script executed inside virtme-ng as
if it was running directly on the host.

This fixes issue #48.

Signed-off-by: Andrea Righi <andrea.righi@canonical.com>

diff --git a/virtme/guest/virtme-init b/virtme/guest/virtme-init
--- a/virtme/guest/virtme-init
+++ b/virtme/guest/virtme-init
@@ -260,6 +260,11 @@ if [[ -n "${user_cmd}" ]]; then
             /dev/virtio-ports/virtme.stderr     \
             /dev/virtio-ports/virtme.dev_stdout \
             /dev/virtio-ports/virtme.dev_stderr
+
+        if [ -e /dev/virtio-ports/virtme.ret ]; then
+            chown ${virtme_user}                \
+                /dev/virtio-ports/virtme.ret
+        fi
     fi
 
     # Fix /dev/stdout and /dev/stderr.
@@ -289,7 +294,13 @@ if [[ -n "${user_cmd}" ]]; then
         else
             setsid bash /tmp/.virtme-script </dev/virtio-ports/virtme.stdin >/dev/virtio-ports/virtme.stdout 2>/dev/virtio-ports/virtme.stderr
         fi
-        log "script returned $?"
+	ret=$?
+        log "script returned {$ret}"
+
+        # Channel exit code to the host.
+        if [ -e /dev/virtio-ports/virtme.ret ]; then
+            echo ${ret} > /dev/virtio-ports/virtme.ret
+        fi
 
         # Hmm.  We should expose the return value somehow.
         sync
