virtme: proper stdin/stdout/stderr redirection with scripts
Virtio serial ports are designed to support a single writer at a time,
which means that only one process or application can write to the port
at any given moment.

When using a virtio serial port, the EBUSY error can occur if multiple
writers are attempting to access the port simultaneously.

This can happen for example when a script running inside the guest tries
to write to /dev/stdout or /dev/stderr directly, that are mapped to the
same virtio serial port already opened to forward stdout and stderr to
the host.

To prevent this problem create two separate virtio serial ports to
handle writes directly to /dev/stdout and /dev/stderr that will be all
redirected to stdout on the host.

Moreover, create independent virtio serial ports for stdout and stderr,
so we can handle stdout/stderr separately, as if we were running the
script natively on the host.

Example:

 $ echo hello | virtme-ng -r --exec "cat -" | md5sum
 b1946ac92492d2347c6235b4d2611184  -
 $ echo hello | virtme-ng -r --exec "cat - >/dev/stderr" | md5sum
 hello
 d41d8cd98f00b204e9800998ecf8427e  -
 $ echo hello | virtme-ng -r --exec "cat - >/dev/stderr" 2>&1 | md5sum
 b1946ac92492d2347c6235b4d2611184  -

This fixes issue #8.

Signed-off-by: Andrea Righi <andrea.righi@canonical.com>

diff --git a/virtme/guest/virtme-init b/virtme/guest/virtme-init
--- a/virtme/guest/virtme-init
+++ b/virtme/guest/virtme-init
@@ -219,14 +219,34 @@ if cat /proc/cmdline |grep -q -E '(^| )virtme.dhcp($| )'; then
 fi
 
 if [[ -x /run/virtme/data/script ]]; then
-    if [[ ! -e "/dev/virtio-ports/virtme.stdin" || ! -e "/dev/virtio-ports/virtme.stdout" ]]; then
-	echo "virtme-init: cannot find script I/O ports; make sure virtio-serial is available"
-	poweroff -f
-	exit 1
+    if [[ ! -e "/dev/virtio-ports/virtme.stdin" ||
+          ! -e "/dev/virtio-ports/virtme.stdout" ||
+          ! -e "/dev/virtio-ports/virtme.stderr" ||
+          ! -e "/dev/virtio-ports/virtme.dev_stdout" ||
+          ! -e "/dev/virtio-ports/virtme.dev_stderr" ]]; then
+        echo "virtme-init: cannot find script I/O ports; make sure virtio-serial is available"
+        poweroff -f
+        exit 1
     fi
 
+    # Fix /dev/stdout and /dev/stderr.
+    #
+    # When using a virtio serial port, the EBUSY error can occur if multiple
+    # writers are attempting to access the port simultaneously. The virtio
+    # serial port is designed to support a single writer at a time, which means
+    # that only one process or application can write to the port at any given
+    # moment.
+    #
+    # For this reason create a separate virtio serial port to handle writes
+    # directly to /dev/stdout and /dev/stderr that will be all redirected to
+    # stdout on the host.
+    rm -f /dev/stdout /dev/stderr
+    ln -s /dev/virtio-ports/virtme.dev_stdout /dev/stdout
+    ln -s /dev/virtio-ports/virtme.dev_stderr /dev/stderr
+
+    # Start the script
     log 'starting script'
-    setsid /run/virtme/data/script </dev/virtio-ports/virtme.stdin >/dev/virtio-ports/virtme.stdout 2>&1
+    setsid /run/virtme/data/script </dev/virtio-ports/virtme.stdin >/dev/virtio-ports/virtme.stdout 2>/dev/virtio-ports/virtme.stderr
     log "script returned $?"
 
     # Hmm.  We should expose the return value somehow.
